### ISSUE TITLE
Emphasize GA account compability

### ISSUE THREAD

**Issue by anissen** [fbricker/haxe-ga#16]
Thanks for creating this project -- it will definitely help me in adding simple analytics for my game :clap: 

However, I had some trouble finding out if it actually worked. I had set up an "Mobile App" google analytics account (I need to tracking from native iOS/Android as well as Web) and nothing was reported. Changing the account type to "Website" made it work beautifully.

The requirement for using the analytics ID of an "Website"-GA account should be emphasized in the readme to help others avoid my (silly?) mistake :+1:

**Comment by fbricker** [comment]
Hi, you're right. I didn't mention that in documentation since I'm considering to add the native SDK for android and iOS in case someone needs to integrate a Google Analytics App ID instead of a Website ID.

But time's running and I never integrated native SDK, so I'll write that on documentation until I have time to integrate the SDK :)

Thanks!
